# Generated by Django 2.2.2 on 2019-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JHappl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
