# Generated by Django 2.2.2 on 2019-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JHappl', '0002_pdf_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
