# Generated by Django 2.2.2 on 2019-07-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JHappl', '0003_auto_20190720_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
