# Generated by Django 2.2.2 on 2019-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JHappl', '0004_rawtextmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtextmodel',
            name='name',
            field=models.CharField(default='sample', max_length=10),
        ),
    ]
