# Generated by Django 2.1.7 on 2019-03-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_interpreter', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='leases/pdfs/')),
            ],
        ),
    ]
